#version 450 core
layout (local_size_x = 32, local_size_y = 32) in;

uniform float u_strength;
uniform float u_far_plane;
uniform float u_near_plane;

layout(rgba8, binding=0) readonly restrict uniform image2D u_input_color_texture;
layout(rgba8, binding=1) writeonly restrict uniform image2D u_output_color_texture;
uniform sampler2D u_input_depth_texture;

const ivec2 neighbors[4] = ivec2[](ivec2(2, 0), ivec2(0, 2), ivec2(-2, 0), ivec2(0, -2));


float readDepthNormalized(in ivec2 coords, in ivec2 texture_size)
{
    float depth = texelFetch(u_input_depth_texture, coords, 0).r;
    depth = depth * 2.0 - 1.0;
    depth = (2.0 * u_near_plane) / (u_far_plane + u_near_plane - depth * (u_far_plane - u_near_plane));// linearize and normalize depth
    return depth;
}


void main(void)
{
    ivec2 texture_size = imageSize(u_input_color_texture);
    if (gl_GlobalInvocationID.x >= texture_size.x || gl_GlobalInvocationID.y >= texture_size.y)
    {
        return;
    }

    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    float depth = readDepthNormalized(coords, texture_size);

    float depth_difference = 0.0;
    for (int i = 0; i < 4; i++)
    {
        ivec2 neighbor_coords = clamp(coords + neighbors[i], ivec2(0, 0), texture_size - 1);
        float neighbor_depth = readDepthNormalized(neighbor_coords, texture_size);
        depth_difference += max(0.0, depth - neighbor_depth);
    }
    depth_difference /= 4.0;

    float strength = 40.0 * u_strength * (1.0 / depth);

    vec4 color = imageLoad(u_input_color_texture, coords);
    imageStore(u_output_color_texture, coords, vec4(color.rgb * exp(-depth_difference * strength), 1.0));
}
