#version 450

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding=0) buffer inputBuffers
{
    uint depthBuffer[];
};

layout (std430, binding=1) buffer inputRGBABuffer
{
    uint rgbaBuffer[];
};

void main(void)
{
    uint invocationID = gl_GlobalInvocationID.x;

    if (invocationID > depthBuffer.length())
        return;

    depthBuffer[invocationID] = floatBitsToUint(1.0f);
    rgbaBuffer[4*invocationID+0] = floatBitsToUint(0.0f);
    rgbaBuffer[4*invocationID+1] = floatBitsToUint(0.0f);
    rgbaBuffer[4*invocationID+2] = floatBitsToUint(0.0f);
    rgbaBuffer[4*invocationID+3] = floatBitsToUint(0.0f);
}