#version 450

#extension GL_ARB_shader_atomic_counters : enable

layout (local_size_x = 1024) in;

uniform vec2 u_FramebufferSize;
uniform mat4 u_ModelViewProjectionMatrix;
uniform float u_threshold;

struct vector3
{
    float x;
    float y;
    float z;
};

layout (std430, binding=0) buffer inputDepthBuffer
{
    uint depthBuffer[];
};

layout (std430, binding=1) buffer inputRGBABuffer
{
    uint rgbaBuffer[];
};

#SHADER_DEFINES // Here the VERTEX_SHADER_OUTPUT_XYZ get placed by the ShaderProgramFactory before compilation of the shader

layout (std430, binding=2) readonly buffer inputPosition
{
    vector3 sourcePosition[];
};

vec3 getPosition()
{
    uint offset = gl_GlobalInvocationID.x;
    return vec3(sourcePosition[offset].x, sourcePosition[offset].y, sourcePosition[offset].z);
}

float getDepth()
{
    vec4 position = vec4(getPosition(), 1.0);
    position = u_ModelViewProjectionMatrix * position;
    position.xyz /= position.w;

    return (position.z + 1.0) / 2.0;
}

#if defined(ATTRIBUTE_INPUT_COLOR)
    layout (std430, binding=3) readonly buffer inputColor
    {
        uint sourceColor[];
    };

    vec3 getColor()
    {
        uint base_offset = gl_GlobalInvocationID.x * 3;

        uint offset_r = base_offset >> 2;     // >> 2 corresponds to / 4 but is potentially faster
        uint offset_g = (base_offset + 1) >> 2;
        uint offset_b = (base_offset + 2) >> 2;

        uint shift_r = base_offset & 3;    // &3 corresponds to %4 but is potentially faster;
        uint shift_g = (base_offset + 1) & 3;
        uint shift_b = (base_offset + 2) & 3;

        float r = float((sourceColor[offset_r] >> 8 * shift_r) & 0xFFu) / 255.0;
        float g = float((sourceColor[offset_g] >> 8 * shift_g) & 0xFFu) / 255.0;
        float b = float((sourceColor[offset_b] >> 8 * shift_b) & 0xFFu) / 255.0;

        return vec3(r, g, b);
    }
#endif

#if defined(ATTRIBUTE_INPUT_NORMAL)
    layout (std430, binding=4) readonly buffer inputNormal
    {
        vector3 sourceNormal[];
    };

    vec3 getNormal()
    {
        uint offset = gl_GlobalInvocationID.x;
        return vec3(sourceNormal[offset].x, sourceNormal[offset].y, sourceNormal[offset].z);
    }
#endif

#if defined(ATTRIBUTE_INPUT_ID)
    layout (std430, binding=5) readonly buffer inputId
    {
        uint sourceId[];
    };

    uint getId()
    {
        return sourceId[gl_GlobalInvocationID.x];
    }
#endif

#if defined(ATTRIBUTE_INPUT_SEGMENT)
    layout (std430, binding=6) readonly buffer inputSegmentId
    {
        uint sourceSegmentId[];
    };

    uint getSegment()
    {
        return inputSegmentId[gl_GlobalInvocationID.x];
    }
#endif

#if defined(ATTRIBUTE_INPUT_CUSTOM_FLOAT)
    layout (std430, binding=7) readonly buffer inputCustom
    {
        float sourceCustom[];
    };

    float getCustom()
    {
        return sourceCustom[gl_GlobalInvocationID.x];
    }
#endif

#if defined(ATTRIBUTE_INPUT_CUSTOM_INT)
    layout (std430, binding=7) readonly buffer inputCustom
    {
        int sourceCustom[];
    };

    int getCustom()
    {
        return sourceCustom[gl_GlobalInvocationID.x];
    }
#endif

#if defined(ATTRIBUTE_INPUT_CUSTOM_UINT)
    layout (std430, binding=7) readonly buffer inputCustom
    {
        uint sourceCustom[];
    };

    uint getCustom()
    {
        return sourceCustom[gl_GlobalInvocationID.x];
    }
#endif

#if defined(ATTRIBUTE_INPUT_CUSTOM_VEC)
    layout (std430, binding=7) readonly buffer inputCustom
    {
        vector3 sourceCustom[];
    };

    vec3 getCustom()
    {
        uint offset = gl_GlobalInvocationID.x;
        return vec3(sourceCustom[offset].x, sourceCustom[offset].y, sourceCustom[offset].z);
    }
#endif

#COLORIZATION

void main(void)
{
    uint globalID = gl_GlobalInvocationID.x;

    if (globalID >= sourcePosition.length())
        return;

    vec4 position = vec4(getPosition(), 1.0);
    position = u_ModelViewProjectionMatrix * position;

    if(abs(position.x) > position.w || abs(position.y) > position.w || abs(position.z) > position.w) {
        return;
    }

    position.xyz /= position.w;

    ivec2 pixelCoords = ivec2((position.xy * 0.5 + 0.5) * u_FramebufferSize);
    int pixelID = pixelCoords.x + pixelCoords.y * int(u_FramebufferSize.x);

    float depth = (position.z + 1.0) / 2.0;
    float current_depth = uintBitsToFloat(depthBuffer[pixelID]);

    if(depth <= current_depth + u_threshold) {
        vec4 color = colorization();
        atomicAdd(rgbaBuffer[4*pixelID+0], int(color.r * 255.0));
        atomicAdd(rgbaBuffer[4*pixelID+1], int(color.g * 255.0));
        atomicAdd(rgbaBuffer[4*pixelID+2], int(color.b * 255.0));
        atomicAdd(rgbaBuffer[4*pixelID+3], 1);
    }
}
