#version 450

#extension GL_KHR_shader_subgroup_arithmetic : enable 
#extension GL_KHR_shader_subgroup_vote : enable  
#extension GL_NV_shader_subgroup_partitioned : enable

layout (local_size_x = 1024) in;

uniform vec2 u_FramebufferSize;
uniform mat4 u_ModelViewProjectionMatrix;

layout (std430, binding=0) buffer inputDepthBuffer
{
    uint depthBuffer[];
};

struct vector3
{
    float x;
    float y;
    float z;
};

layout (std430, binding=2) readonly buffer inputPosition
{
    vector3 sourcePosition[];
};

vec3 getPosition()
{
    uint offset = gl_GlobalInvocationID.x;
    return vec3(sourcePosition[offset].x, sourcePosition[offset].y, sourcePosition[offset].z);
}

void main(void)
{
    uint globalID = gl_GlobalInvocationID.x;

    if (globalID >= sourcePosition.length())
        return;

    vec4 position = vec4(getPosition(), 1.0);
    position = u_ModelViewProjectionMatrix * position;

    if(abs(position.x) > position.w || abs(position.y) > position.w || abs(position.z) > position.w) {
        return;
    }

    position.xyz /= position.w;

    uint depth = floatBitsToUint((position.z + 1.0) / 2.0);

    ivec2 pixelCoords = ivec2((position.xy * 0.5 + 0.5) * u_FramebufferSize);
    int pixelID = pixelCoords.x + pixelCoords.y * int(u_FramebufferSize.x);

    uint current_depth = depthBuffer[pixelID];
    if(depth < current_depth) {
        atomicMin(depthBuffer[pixelID], depth);
    }
}
