#version 460 core
layout (local_size_x = 1024) in;

/*===============================================*/
/* INPUTS                                        */
/*===============================================*/

uniform uint u_level_start;
uniform uint u_level_end;

// camera-related uniforms
uniform mat4x4 u_mvp;
uniform vec4 u_camera_frustum[6];
uniform vec3 u_camera_position;
uniform vec3 u_camera_forward;
uniform vec3 u_camera_right;
uniform float u_far_plane;
uniform float u_camera_fov;
uniform int u_screen_width;
uniform int u_screen_height;

// priority/LOD-related uniforms
uniform int u_projection_function;
uniform int u_projection_size_render_threshold;

uniform int u_distance_function;

uniform float u_projection_factor;
uniform float u_distance_factor;
uniform float u_centrality_factor;
uniform bool u_use_recency_of_use;

const float PRIORITY_THRESHOLD = 0.001f;

// input and output buffers
struct Node
{   vec3 bbox_min;
    float is_leaf;
    vec3 bbox_max;
    uint parent_index_and_render_flag;  // contains a bool in the highest-order bit, indicating, whether the parent will be rendered. The rest of the bits specify the parent index.
};

layout(std430, binding=0) restrict buffer nodes_buffer
{
    Node nodes[];
};

layout(std430, binding=1) restrict buffer result_buffer
{
    float results[];
};

layout(std430, binding=2) restrict buffer recency_buffer
{
    float last_recency[];
};

/*===============================================*/
/* HELPER FUNCTIONS                              */
/*===============================================*/

vec3 project(vec3 point)
{
	vec4 projected = u_mvp * vec4(point, 1.0f);
	return (projected.xyz / projected.w + vec3(1.0f)) * 0.5f;
}

bool point_outside_box(vec3 box_min, vec3 box_max, vec3 point)
{
	return (point.x < box_min.x || point.x > box_max.x ||
			point.y < box_min.y || point.y > box_max.y ||
			point.z < box_min.z || point.z > box_max.z);
}

bool in_view_frustum(vec3 bbox_min, vec3 bbox_max)
{
	for(int i = 0; i < 6; i++)
	{
		vec4 plane = u_camera_frustum[i];

		vec3 mask_positive = vec3(float(plane.x >= 0.0f), float(plane.y >= 0.0f), float(plane.z >= 0.0f));
		vec3 mask_negative = vec3(1.0f) - mask_positive;

		vec3 p_vertex = bbox_max * mask_positive + bbox_min * mask_negative;
		float distance_p = dot(plane.xyz, p_vertex) + plane.w;

		if(distance_p < 0.0f)
			return false;
	}
	return true;
}

/*===============================================*/
/* FUNCTIONS FOR DETERMINING LOD                 */
/*===============================================*/

// most accurate method, requires 8 projections (used in VMV 2025 measurements)
ivec2 full_projection(vec3 bbox_min, vec3 bbox_max) // returns (longest screen-space AABB side's full length, longest screen-space AABB side's visible length)
{
	if (!point_outside_box(bbox_min, bbox_max, u_camera_position))
	{
		return ivec2(u_screen_width, u_screen_width);
	}

	if(!in_view_frustum(bbox_min, bbox_max))
	{
		return ivec2(0);
	}

	vec2 screen_bbox_min = vec2(10.0f);
	vec2 screen_bbox_max = vec2(-10.0f);

	vec3 projected = project(bbox_min);
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(vec3(bbox_max.x, bbox_min.y, bbox_min.z));
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(vec3(bbox_min.x, bbox_max.y, bbox_min.z));
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(vec3(bbox_min.x, bbox_min.y, bbox_max.z));
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(vec3(bbox_max.x, bbox_max.y, bbox_min.z));
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(vec3(bbox_min.x, bbox_max.y, bbox_max.z));
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(vec3(bbox_max.x, bbox_min.y, bbox_max.z));
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	projected = project(bbox_max);
	screen_bbox_min = min(screen_bbox_min, projected.xy);
	screen_bbox_max = max(screen_bbox_max, projected.xy);

	// compute longest side of the AABB of the projected AABB (also outside the clip space) -> used for LOD selection
	int pixel_x = int((screen_bbox_max.x - screen_bbox_min.x) * float(u_screen_width));
	int pixel_y = int((screen_bbox_max.y - screen_bbox_min.y) * float(u_screen_height));
	int longest_side = max(pixel_x, pixel_y);

	// compute visible longest side -> used for priority computation
	screen_bbox_max = clamp(screen_bbox_max, vec2(0.0), vec2(1.0));
	screen_bbox_min = clamp(screen_bbox_min, vec2(0.0), vec2(1.0));
	pixel_x = int((screen_bbox_max.x - screen_bbox_min.x) * float(u_screen_width));
	pixel_y = int((screen_bbox_max.y - screen_bbox_min.y) * float(u_screen_height));
	return ivec2(longest_side, max(pixel_x, pixel_y));
}

// approximation using the longest screen-space diagonal: requires only two projections
ivec2 diagonal_projection(vec3 bbox_min, vec3 bbox_max)
{
	if (!point_outside_box(bbox_min, bbox_max, u_camera_position))
	{
		return ivec2(u_screen_width, u_screen_width);
	}

	if(!in_view_frustum(bbox_min, bbox_max))
	{
		return ivec2(0);
	}

	// get the p-vertex and n-vertex for the plane defined by the camera right vector -> these vertices form the longest bbox diagonal in screen-space
	vec3 mask_positive = vec3(float(u_camera_right.x >= 0.0f), float(u_camera_right.y >= 0.0f), float(u_camera_right.z >= 0.0f));
	vec3 mask_negative = vec3(1.0f) - mask_positive;

	vec3 p_vertex = bbox_max * mask_positive + bbox_min * mask_negative;
	vec3 n_vertex = bbox_max * mask_negative + bbox_min * mask_positive;

	vec2 p_projected = project(p_vertex).xy;
	vec2 n_projected = project(n_vertex).xy;

	// compute longest side of the AABB of the projected AABB (also outside the clip space) -> used for LOD selection
	int pixel_x = int((p_projected.x - n_projected.x) * float(u_screen_width));
	int pixel_y = int((p_projected.y - n_projected.y) * float(u_screen_height));
	int longest_side = max(pixel_x, pixel_y);

	// compute visible longest side -> used for priority computation
	p_projected = clamp(p_projected, vec2(0.0), vec2(1.0));
	n_projected = clamp(n_projected, vec2(0.0), vec2(1.0));
	pixel_x = int((p_projected.x - n_projected.x) * float(u_screen_width));
	pixel_y = int((p_projected.y - n_projected.y) * float(u_screen_height));

	return ivec2(longest_side, max(pixel_x, pixel_y));
}

// approximation using bounding sphere: no multiplication with projection matrix required
ivec2 sphere_projection(vec3 bbox_min, vec3 bbox_max)
{
	if (!point_outside_box(bbox_min, bbox_max, u_camera_position))
	{
		return ivec2(u_screen_width, u_screen_width);
	}

	if(!in_view_frustum(bbox_min, bbox_max))
	{
		return ivec2(0);
	}

	vec3 center = bbox_min + (bbox_max - bbox_min) * 0.5f;
	float radius = length(bbox_max - center);
	float dist = length(u_camera_position - center);
	float screen_diameter = 2.0 * radius / (dist * tan(u_camera_fov * 0.5f));

	// compute longest side of the AABB of the projected AABB (also outside the clip space) -> used for LOD selection
	int pixel_x = int(screen_diameter * float(u_screen_width));
	int pixel_y = int(screen_diameter * float(u_screen_height));
	int longest_side = max(pixel_x, pixel_y);

	// compute visible longest side -> used for priority computation
	screen_diameter = clamp(screen_diameter, 0.0, 1.0);
	pixel_x = int(screen_diameter * float(u_screen_width));
	pixel_y = int(screen_diameter * float(u_screen_height));

	return ivec2(longest_side, max(pixel_x, pixel_y));
}

/*===============================================*/
/* PRIORITY FUNCTIONS                            */
/*===============================================*/

float center_distance(vec3 bbox_min, vec3 bbox_max, vec3 camera_position)
{
	return max(0.0f, 1.0f - length(camera_position - (bbox_min + (bbox_max - bbox_min) * 0.5f)) / u_far_plane);
}

float closest_corner_distance(vec3 bbox_min, vec3 bbox_max, vec3 camera_position)
{
	vec3 closest_corner_dir = min(abs(bbox_min - camera_position), abs(bbox_max - camera_position));
	return clamp(1.0f - length(closest_corner_dir) / u_far_plane, 0.0f, 1.0f);
}

float centrality(vec3 bbox_min, vec3 bbox_max, vec3 camera_position, vec3 camera_forward)
{
	vec3 center = bbox_min + (bbox_max - bbox_min) * 0.5f;
	vec3 camera_to_center = normalize(center - camera_position);
	return dot(camera_to_center, camera_forward) * 0.5f + 0.5f;
}


/*===============================================*/
/* MAIN                                          */
/*===============================================*/

const uint PARENT_INDEX_MASK = 0x7FFFFFFFu;  // parent index is stored in the lower bits

void main(void)
{
	uint node_index = u_level_start + gl_GlobalInvocationID.x;
	if(node_index >= u_level_end)
		return;

	// Fetch required data
	Node node = nodes[node_index];
	uint parent_index = node.parent_index_and_render_flag & PARENT_INDEX_MASK;
	uint parent_rendered = 0;
	if(parent_index != PARENT_INDEX_MASK) // the root has set the index mask as parent index. Skip it.
		parent_rendered = nodes[parent_index].parent_index_and_render_flag >> 31;  // highest order contains the render flag (whether the parent will be rendered).

	float screen_max = float(max(u_screen_width, u_screen_height));
	float priority = 0.0f;
	ivec2 projection;

    // Compute projected size for LOD selection
	if(u_projection_function == 1)
	{
		projection = full_projection(node.bbox_min, node.bbox_max);
	}
	else if(u_projection_function == 2)
	{
		projection = diagonal_projection(node.bbox_min, node.bbox_max);
	}
	else if(u_projection_function == 3)
	{
		projection = sphere_projection(node.bbox_min, node.bbox_max);
	}

	// Compute priority based on the user settings

	// AABB (for leaf and inner nodes that are rendered)
	float aabb_priority = clamp(float(projection.y) / screen_max, 0.0, 1.0) * u_projection_factor;

	// DISTANCE
  	if(u_distance_function == 1)
	{
		priority += center_distance(node.bbox_min, node.bbox_max, u_camera_position) * u_distance_factor;
	}
	else if(u_distance_function == 2)
	{
		priority += closest_corner_distance(node.bbox_min, node.bbox_max, u_camera_position) * u_distance_factor;
	}

	// CENTRALITY
	priority += centrality(node.bbox_min, node.bbox_max, u_camera_position, u_camera_forward) * u_centrality_factor;

	// determine whether to render and compute additional priority factors
	if(node.is_leaf > 0.0f)
	{
		priority += aabb_priority;

		if(parent_rendered == 0 && projection.x > 0)
		{
			priority += 100.0f;
			last_recency[node_index] = 1.0;
		}
		else if (u_use_recency_of_use)  // RECENCY
		{
			float recency = max(0.0f, last_recency[node_index] - 0.001f);   // decay recency
			priority += recency; 
			last_recency[node_index] = recency;
		}

		if (priority < PRIORITY_THRESHOLD)
			priority = 0.0f;
		results[node_index] = priority;
		return;
	}

	uint should_render = parent_rendered;
	if(parent_rendered == 0 && projection.x > 0 && projection.x < u_projection_size_render_threshold)
	{
		priority += 100.0f + aabb_priority;
		should_render = 1;
		last_recency[node_index] = 1.0;
	}
	else{
		float distance_from_threshold = abs(projection.x - u_projection_size_render_threshold);
		priority += (1.0 - clamp(distance_from_threshold / float(u_projection_size_render_threshold), 0.0, 1.0)) * u_projection_factor; // AABB for inner nodes that are not rendered

		if(u_use_recency_of_use){   // RECENCY
			float recency = max(0.0f, last_recency[node_index] - 0.001f);   // decay recency
			priority += recency; 
			last_recency[node_index] = recency;
		}
	}

	nodes[node_index].parent_index_and_render_flag = parent_index | (should_render << 31);  // write render flag back
	if (priority < PRIORITY_THRESHOLD)
		priority = 0.0f;
	results[node_index] = priority;
}